apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  labels:
    app: todo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: 192.168.49.1:5100/todo-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4588

          envFrom:
            - configMapRef:
                name: todo-backend-config
            - secretRef:
                name: todo-backend-secret